### ISSUE TITLE
Unexpected token crash

### ISSUE THREAD

**Issue by ghost** [vutran/composer-version#1]
Hi there,
I'm trying to run `composer-version` and I get this crash. I suppose it is related to the  fact that I only have node 4 configured and not node 6 with all the latest javascript bells and whistles?

```
const { getNextVersion } = require('./utils');
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/composer-version/cli.js:3:25)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

Thank you,

**Comment by vutran** [comment]
Yes, that is correct. Feel free to submit a PR to make it compatible for node 4 if you have time. Otherwise, I can take a look at this later this week.

All you need to do is remove the destructuring patterns.

```
const utils = require('./utils');

const getNextVersion = utils.getNextVersion;
```

**Comment by vutran** [comment]
This should be address in the latest release `v0.2.0` (tested on node `v4.5.0`)
